name: Run Tests

on:
  push:
    branches:
    - main
    paths-ignore:
    - README.md

  pull_request:
    branches:
    - main
    paths-ignore:
    - README.md

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  unit-and-integration-tests:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Run tests
      run: |
        make test
      