name: Run Tests

on:
  push:
    branches:
    - main
    paths-ignore:
    - README.md

  pull_request:
    branches:
    - main
    paths-ignore:
    - README.md

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  unit-and-integration-tests:
    runs-on: ubuntu-22.04
    needs: check-generate

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Run tests
      run: |
        make test
      